### ISSUE TITLE
App freezes upon first use (after installation)

### ISSUE THREAD

**Issue by tonyliang19** [sticky-pi/sticky-pi-android-harvester#1]
-Ask for permission in the first use
-Location and Logo are not showing
-Check permission grants to the app in the device

**Comment by qgeissmann** [comment]
fixed by https://github.com/sticky-pi/sticky-pi-android-harvester/commit/723b96d7ce8228a89bfdaa46bc0ce62d1b5084fe#diff-d3ca35d520bb4ed004234715fe8fce44012cc5cd24ff7fce41550609a50beadcR110
